# SIGN UP
POST {{baseUrl}}/customers 
Content-Type: application/json

{
    "email": "abcd@gmail.com",
    "password": "password",
    "firstName": "Icheka",
    "lastName": "Ozuru",
    "country": "Nigeria"
}
###

# LOGIN
POST {{baseUrl}}/customers/login
Content-Type: application/json

{
    "email": "abcd@gmail.com",
    "password": "password"
}
###

# ACTIVATE PRODUCT
PATCH {{baseUrl}}/products/activate
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
    
}